[package]
name = "libremarkable"
version = "0.3.2"
authors = ["Can Selcik <contact@cselcik.com>"]
is-it-maintained-issue-resolution = { repository = "https://github.com/canselcik/libremarkable" }
is-it-maintained-open-issues = { repository = "https://github.com/canselcik/libremarkable" }
repository = "https://github.com/canselcik/libremarkable"
maintenance = { status = "actively-developed" }
license = "MIT"
description = "The only publicly available Framework for developing applications for the Remarkable Paper Tablet w/ Low Latency Partial Refresh Support"
readme = "README.md"
exclude = [ "reference-material/*", "legacy-c-impl/*", "private/*" ]

[build]
target= "armv7-unknown-linux-gnueabihf"

[dependencies]
log = "0.4.1"
env_logger = "0.5.6"
ioctl-gen = "0.1.0"
libc = "0.2.37"
mmap = "0.1.1"
rusttype = "0.4.1"
evdev = "0.10.1"
epoll = "3.1.1"
image = "0.18.0"
line_drawing = "0.7.0"
hlua = "0.4.1"
aabb-quadtree = "0.1.0"
zstd = "0.4.14"
stopwatch = "0.0.7"
atomic = {version = "0.4", features = ["nightly"]}

[features]
enable-runtime-benchmarking = []

[profile.release]
debug = true

[[example]]
name = "spy"
path = "examples/spy.rs"
crate-type = ["dylib"]

[[example]]
name = "demo"
path = "examples/demo.rs"
crate-type = ["bin"]

[[example]]
name = "demo-modified"
path = "examples/demo-modified.rs"
crate-type = ["bin"]

[[example]]
name = "live"
path = "examples/live.rs"
crate-type = ["bin"]

[dev-dependencies]
# For spy
redhook = "0.1.1"
libc = "0.2.37"
lazy_static = "1.0.0"
# For demo
chrono = "0.4.0"
# For live
tiny_http = "0.6.0"
